### ISSUE TITLE
Búsqueda en trámites participados arroja Error 403

### ISSUE THREAD

**Issue by carlos-riquelme** [e-gob/SIMPLE#555]
Al buscar un trámite utilizando el buscador en el Historial de trámites, se produce un error 403. Ojo con la url que muestra en el ejemplo:

![image](https://cloud.githubusercontent.com/assets/17183866/13155392/3c1daf78-d65c-11e5-9b3a-2dedc7a750f4.png)

**Comment by manuelmunoz00** [comment]
Estimado Carlos,

Hemos revisado el issue y no presenta problemas. Podrías revisar tu configuración apache y la documentación de Simple para ver si están habilitadas las opciones requeridas.

**Comment by carlos-riquelme** [comment]
Lo revisé y tiene que ver con el preg_replace que aparece en la línea 5 del archivo participados.php (\application\views\tramites\participados.php). Cuando uso mi ambiente de pruebas como en el pantallazo, la función elimina el '127', tal como debería hacerlo de acuerdo al código. Por el contrario, cuando uso localhost en lugar de la ip, no se reemplaza nada de la dirección y la página no cambia. Todo eso está de acuerdo al código.
Ahora, se me ocurre preguntar cuál es el objetivo de usar preg_replace en la búsqueda de participados.php y no hacerlo en la búsqueda de inbox.php (\application\views\etapas\inbox.php). De la misma forma, tengo al configuración de apache de acuerdo al manual de instalación y todas las opciones habilitadas, pero sigo sin obtener resultados en las búsquedas:

![image](https://cloud.githubusercontent.com/assets/17183866/13220038/7b0a0418-d952-11e5-98d4-fb68bfb2c1a8.png)

**Comment by manuelmunoz00** [comment]
Estimado,

Podrías subir una captura de pantalla del estado de configuración del sphinx y del php.

Nos preocupa ya que lo que nos comentas es primera vez que ocurre.

Saludos.

**Comment by carlos-riquelme** [comment]
Lo cierro porque todo se debía a un problema con el servicio de Sphinx. 

Saludos.
