### ISSUE TITLE
Ojo con este fix de CI 

### ISSUE THREAD

**Issue by carlos-riquelme** [e-gob/SIMPLE#556]
[Fix Common::get_config() error in PHP 5.6 - fix #3302](https://github.com/bcit-ci/CodeIgniter/commit/69b02d0f0bc46e914bed1604cfbd9bf74286b2e3)

Al ingresar por primera vez al backend después de instalar y configurar, aparece este error:

![image](https://cloud.githubusercontent.com/assets/17183866/13178128/1514c3ee-d6fc-11e5-8e4a-c22bbaf65b82.png)

El fix lo soluciona.

**Comment by manuelmunoz00** [comment]
Estimado Carlos,

Agradecemos tu comentario. Hemos realizado el cambio para este fix. Saludos.
