### ISSUE TITLE
tengo un problema con la parte de buscar un tramite

### ISSUE THREAD

**Issue by luisfelipenunezxd** [e-gob/SIMPLE#608]
hola buenos dias.  tengo un problema con la parte de buscar un tramite no me busca

**Comment by luisfelipenunezxd** [comment]
![error](https://cloud.githubusercontent.com/assets/28625439/25997457/7756613c-36f2-11e7-8842-5e3e6b31464d.png)

**Comment by carlos-riquelme** [comment]
¿Cuál es el estado de Sphinx? Sphinxserver es la herramienta que utiliza Simple para las búsquedas de texto.

**Comment by manuelmunoz00** [comment]
En la documentación están los pasos para habilitar el módulo de búsquedas de Sphinx.

**Comment by carlos-riquelme** [comment]
Exacto. Yo también tuve problemas con las búsquedas y era porque el servicio de Sphinx no estaba iniciado.

**Comment by luisfelipenunezxd** [comment]
muchas gracias amigos ese era el problema pero aora no puedo instalar el servidor . si me pudieran echar una mano se los agradeceria mucho 
![sin titulo](https://cloud.githubusercontent.com/assets/28625439/26080066/eab82c30-3992-11e7-8552-4813e2f8a5b9.png)

**Comment by carlos-riquelme** [comment]
Probaste agregándole la opción `--rotate`?

Lo otro, la ruta del archivo .conf debería usar backslash `\`

**Comment by luisfelipenunezxd** [comment]
muchas gracias amigos
